type Flight {
  id: ID
  origin: String
  destination: String
  price: Float
}

input inputFlightType {
  type: String
  origin: String
  destination: String
  price: Float
}

type Mutation {
  addFlight(body: inputFlightType): Flight
}

type Query {
  flightList: [Flight]
  flight(id: ID): Flight
}
