import type { GetServerSideProps, InferGetServerSidePropsType, NextPage } from 'next';

import Head from 'next/head';

import styles from '@/styles/Home.module.css';
import { SimpleBookingDashboardProps } from '@/interfaces/interfaces';
import { Place } from "@/graphql/generated/schemaType";
import { PlaceCardList } from '@/src/PlaceCardList';

const Home: NextPage<InferGetServerSidePropsType<typeof getServerSideProps>> = ({placeList}) => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <PlaceCardList placeList={placeList} />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

const QUERY: string = `
query GetPlaceList {
  placeList {
    id
    desciption
    mainPhoto
    photos
    priceByNight
  }
} 
`;

export const getServerSideProps: GetServerSideProps<SimpleBookingDashboardProps> = async () => {

  let placeList: Place[] = [];
  try {
     const response = await fetch("http://localhost:3000/api/graphql", {
      method: "POST",
      body: JSON.stringify({
        query: QUERY
      }),
      headers: {"content-type": "application/json"}
     });
     
     if (response.status === 200) {
        const json = await response.json();
        placeList = json.data.placeList;
     }
  } catch (err) {
     console.error(err);
  }

  return {
    props: {
      placeList
    }
  };
};

export default Home;
