import type { GetServerSideProps, InferGetServerSidePropsType, NextPage } from 'next';

import Head from 'next/head';

import styles from '@/styles/Home.module.css';
import { SimpleBookingDashboardProps } from '@/interfaces/interfaces';
import { Flight, Place } from "@/graphql/generated/schemaType";
import { CardList } from '@/src/CardList';

const Home: NextPage<InferGetServerSidePropsType<typeof getServerSideProps>> = ({placeList, flightList}) => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <CardList headline="Accommodations" list={placeList} />
        <CardList headline="Flights" list={flightList} />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

// TODO might be better to move this into a separate file when more queries will be needed.
const QUERY: string = `
query GetPlaceAndFlightList {
  placeList {
    __typename
    id
    desciption
    mainPhoto
    photos
    priceByNight
  }
  flightList {
    __typename
    id
    origin
    destination
    price
  }
} 
`;

export const getServerSideProps: GetServerSideProps<SimpleBookingDashboardProps> = async () => {

  let placeList: Place[] = [];
  let flightList: Flight[] = [];
  try {
    // TODO fetching data should be improved. Better switch to a library like apollo.
     const response = await fetch("http://localhost:3000/api/graphql", {
      method: "POST",
      body: JSON.stringify({
        query: QUERY
      }),
      headers: {"content-type": "application/json"}
     });
     
     if (response.status === 200) {
        const json = await response.json();
        placeList = json.data.placeList;
        flightList = json.data.flightList;
     }
  } catch (err) {
     console.error(err);
  }

  return {
    props: {
      placeList,
      flightList
    }
  };
};

export default Home;
